### ISSUE TITLE
Errors on plugin activation

### ISSUE THREAD

**Issue by chrisaldrich** [jackjamieson2/yarns-indie-reader#1]
Two errors thrown upon plugin activation:

Notice: has_cap was called with an argument that is deprecated since version 2.0.0! Usage of user levels is deprecated. Use capabilities instead. in /htdocs/wp-includes/functions.php on line 4031

Warning: Cannot modify header information - headers already sent by (output started at /htdocs//wp-includes/functions.php:4031) in /htdocs/wp-admin/includes/misc.php on line 1114

No other plugins running. Using WP version 4.9.4,

**Comment by jackjamieson2** [comment]
Thanks Chris! I'll check these out and post a reply once they're fixed
