### ISSUE TITLE
Uncaught ArgumentCountError: Too few arguments to function yarns_reader_new_subscription()

### ISSUE THREAD

**Issue by cedricdekimpe** [jackjamieson2/yarns-indie-reader#6]
I just installed this plugin - while it seemed perfect to me, I ran accros this error trying to add a subscription to your site : 

`PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function yarns_reader_new_subscription(), 1 passed in /srv/data/web/vhosts/mysite/htdocs/wp-includes/class-wp-hook.php on line 286 and exactly 4 expected in /srv/data/web/vhosts/mysite/htdocs/wp-content/plugins/yarns-indie-reader-master/yarns_reader.php:790`

Please let me know if you need more info.

Also posted on [cedric.io](https://cedric.io/2018/09/26/uncaught-argumentcounterror-too-few-arguments-to-function-yarns_reader_new_subscription/)

**Comment by jackjamieson2** [comment]
Hi @cedricbousmanne,

**Comment by jackjamieson2** [comment]
Hi @cedricbousmanne,

I wasn't able to reproduce that error, but I did see a potential error in my code that might have caused it. 

Could you try downloading the most recent master? 

If you still have the same error could you let me know the URL of the feed to which your are trying to subscribe? That might help narrow things down, or at least help me replicate the issue.

As for readers in general, most of my attention is now on http://github.com/jackjamieson2/yarns-microsub-server - it's still in progress but close to stable.
